/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelcentralflightmanagementsystem;

import java.sql.*;

/**
 *
 * @author the_scs
 */
public class AircraftManagementUI extends javax.swing.JFrame {

    private Object MySQLConnection;

    
    public AircraftManagementUI() {
        initComponents();
        
        if (!SessionManager.isLoggedIn()) {
            lblName.setVisible(false);
        } else {
            lblName.setText(SessionManager.getLoggedInUsername());
        }

    }
    private static Connection connection = null;

    public static Connection getConnection() {
        if (connection == null) {
            try {
                // Get the database connection parameters
                String url = "jdbc:mysql://localhost:3306/travelcentral";
                String username = "root";
                String password = "b!Q204XaPaFi";

                // Create a new connection to the database
                connection = DriverManager.getConnection(url, username, password);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        return connection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jButtonUpdate = new javax.swing.JButton();
        pnlHead = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblTravel = new javax.swing.JLabel();
        lblCentral = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlSide = new javax.swing.JPanel();
        btnFlightManagement = new javax.swing.JButton();
        btnUserManagement = new javax.swing.JButton();
        btnHotelManagement = new javax.swing.JButton();
        btnAirportManagement = new javax.swing.JButton();
        btnAircraftManagement = new javax.swing.JButton();
        lblHotels = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1526, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1540, 580));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1539, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1539, 807));
        jPanel2.setPreferredSize(new java.awt.Dimension(1539, 807));
        jPanel2.setLayout(null);

        jLabel1.setText("Please insert the ID of the aircraft you would like to update: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(670, 280, 350, 20);

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldID);
        jTextFieldID.setBounds(1020, 270, 270, 40);

        jLabelStatus.setText("Status");
        jPanel2.add(jLabelStatus);
        jLabelStatus.setBounds(670, 400, 70, 20);

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grounded", "Under Maintenance", "Flying", "Scheduled", "On Hold" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxStatus);
        jComboBoxStatus.setBounds(670, 420, 100, 30);

        jButtonUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUpdate);
        jButtonUpdate.setBounds(1170, 480, 130, 40);

        pnlHead.setBackground(new java.awt.Color(0, 0, 0));
        pnlHead.setPreferredSize(new java.awt.Dimension(1536, 100));
        pnlHead.setLayout(null);

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlHead.add(btnLogOut);
        btnLogOut.setBounds(1430, 30, 80, 30);

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlHead.add(btnHome);
        btnHome.setBounds(1350, 30, 80, 30);

        lblTravel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblTravel.setForeground(new java.awt.Color(255, 255, 255));
        lblTravel.setText("T R A V E L");
        pnlHead.add(lblTravel);
        lblTravel.setBounds(60, 30, 70, 16);

        lblCentral.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblCentral.setForeground(new java.awt.Color(255, 255, 255));
        lblCentral.setText("C E N T R A L");
        pnlHead.add(lblCentral);
        lblCentral.setBounds(60, 50, 90, 15);

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Full Name");
        pnlHead.add(lblName);
        lblName.setBounds(0, 40, 1540, 16);

        jPanel2.add(pnlHead);
        pnlHead.setBounds(0, 0, 1536, 100);

        pnlSide.setBackground(new java.awt.Color(0, 0, 0));
        pnlSide.setLayout(null);

        btnFlightManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnFlightManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnFlightManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnFlightManagement.setText("FLIGHT MANAGEMENT");
        btnFlightManagement.setBorderPainted(false);
        btnFlightManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnFlightManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnFlightManagement);
        btnFlightManagement.setBounds(0, 210, 400, 40);

        btnUserManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnUserManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnUserManagement.setText("USER MANAGEMENT");
        btnUserManagement.setBorderPainted(false);
        btnUserManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnUserManagement);
        btnUserManagement.setBounds(0, 250, 400, 40);

        btnHotelManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnHotelManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnHotelManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnHotelManagement.setText("HOTEL MANAGEMENT");
        btnHotelManagement.setBorderPainted(false);
        btnHotelManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnHotelManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnHotelManagement);
        btnHotelManagement.setBounds(0, 290, 400, 40);

        btnAirportManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnAirportManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnAirportManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnAirportManagement.setText("AIRPORT MANAGEMENT");
        btnAirportManagement.setBorderPainted(false);
        btnAirportManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnAirportManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirportManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnAirportManagement);
        btnAirportManagement.setBounds(0, 330, 400, 40);

        btnAircraftManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnAircraftManagement.setText("AIRCRAFT MANAGEMENT");
        btnAircraftManagement.setBorderPainted(false);
        btnAircraftManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnAircraftManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAircraftManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnAircraftManagement);
        btnAircraftManagement.setBounds(0, 370, 400, 40);

        jPanel2.add(pnlSide);
        pnlSide.setBounds(0, 100, 400, 1440);

        lblHotels.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblHotels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHotels.setText("Aircraft Status Management");
        jPanel2.add(lblHotels);
        lblHotels.setBounds(400, 110, 1140, 120);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed

        // Get the aircraft ID from the text field
        int aircraftID = Integer.parseInt(jTextFieldID.getText());

        if (connection == null) {
            try {
                // Get the database connection parameters
                String url = "jdbc:mysql://localhost:3306/travelcentral";
                String username = "root";
                String password = "b!Q204XaPaFi";

                Statement statement = connection.createStatement();

                // Create the SELECT query
                String query = "SELECT aircraftstatus FROM aircraft WHERE aircraftID = " + aircraftID;

                // Execute the query and get the results
                ResultSet results = statement.executeQuery(query);

                // Get the status of the aircraft
                String status = results.getString("aircraftstatus");
                // Close the ResultSet and Statement objects
                results.close();
                statement.close();

                // Update the status of the aircraft
                updateAircraftStatus(aircraftID, status);

                // Close the Connection object
                connection.close();

                // Create a new connection to the database
                connection = DriverManager.getConnection(url, username, password);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        if (connection == null) {
            try {
                // Get the database connection parameters
                String url = "jdbc:mysql://localhost:3306/travelcentral";
                String username = "root";
                String password = "b!Q204XaPaFi";

                String status = (String) jComboBoxStatus.getSelectedItem();

                // Get the aircraft ID from the text field
                int aircraftID = Integer.parseInt(jTextFieldID.getText());
                // Create a new connection to the database
                connection = DriverManager.getConnection(url, username, password);
                // Create a new Statement object
                Statement statement = connection.createStatement();

                // Create the UPDATE query
                String query = "UPDATE aircraft SET aircraftstatus = '" + status + "' WHERE aircraftID = " + aircraftID;

                // Execute the query
                statement.executeUpdate(query);

                // Close the Statement and Connection objects
                statement.close();
                connection.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            System.exit(0);
        }


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed


    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        AdminOverviewUI adminOverview = new AdminOverviewUI();
        adminOverview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnFlightManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightManagementActionPerformed
        FlightManagementUI flightManagement = new FlightManagementUI();
        flightManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlightManagementActionPerformed

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        UserManagementUI userManagement = new UserManagementUI();
        userManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnHotelManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelManagementActionPerformed
        HotelManagementUI hotelManagement = new HotelManagementUI();
        hotelManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHotelManagementActionPerformed

    private void btnAirportManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirportManagementActionPerformed
        AirportManagementUI airportManagement = new AirportManagementUI();
        airportManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAirportManagementActionPerformed

    private void btnAircraftManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAircraftManagementActionPerformed
        
    }//GEN-LAST:event_btnAircraftManagementActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LogOutUI logOut = new LogOutUI();

        logOut.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AircraftManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AircraftManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AircraftManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AircraftManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AircraftManagementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAircraftManagement;
    private javax.swing.JButton btnAirportManagement;
    private javax.swing.JButton btnFlightManagement;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHotelManagement;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JLabel lblCentral;
    private javax.swing.JLabel lblHotels;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables

    private void updateAircraftStatus(int aircraftID, String status) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
