package travelcentralflightmanagementsystem;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author the_scs
 */
public class BookingViewUI extends javax.swing.JFrame {

    private ProgramManager programManager;

    public BookingViewUI() {

        programManager = new ProgramManager();

        initComponents();

        if (!SessionManager.isLoggedIn()) {
            lblName.setVisible(false);
            btnLogOut.setVisible(false);
        } else {
            lblName.setText(SessionManager.getLoggedInUsername());
        }

        int userID = SessionManager.getLoggedInUser().getUserID();
        DefaultTableModel bookedFlightsTableModel = programManager.getBookedFlightsForUser(userID);
        jTable1.setModel(bookedFlightsTableModel);
        jTable1.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        lblTravel = new javax.swing.JLabel();
        lblCentral = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnBackToSearch = new javax.swing.JButton();
        btnBookaHotel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1536, 1536));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1536, 1536));
        jPanel1.setLayout(null);

        pnlHead.setBackground(new java.awt.Color(0, 0, 0));
        pnlHead.setPreferredSize(new java.awt.Dimension(1536, 100));
        pnlHead.setLayout(null);

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlHead.add(btnLogOut);
        btnLogOut.setBounds(1430, 30, 80, 30);

        lblTravel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblTravel.setForeground(new java.awt.Color(255, 255, 255));
        lblTravel.setText("T R A V E L");
        pnlHead.add(lblTravel);
        lblTravel.setBounds(60, 30, 70, 16);

        lblCentral.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblCentral.setForeground(new java.awt.Color(255, 255, 255));
        lblCentral.setText("C E N T R A L");
        pnlHead.add(lblCentral);
        lblCentral.setBounds(60, 50, 90, 15);

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Full Name");
        pnlHead.add(lblName);
        lblName.setBounds(0, 40, 1540, 16);

        btnBackToSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnBackToSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToSearch.setText("Back To Search");
        btnBackToSearch.setBorder(null);
        btnBackToSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToSearchActionPerformed(evt);
            }
        });
        pnlHead.add(btnBackToSearch);
        btnBackToSearch.setBounds(1340, 30, 90, 30);

        btnBookaHotel.setBackground(new java.awt.Color(0, 0, 0));
        btnBookaHotel.setForeground(new java.awt.Color(255, 255, 255));
        btnBookaHotel.setText("Book a Hotel");
        btnBookaHotel.setBorder(null);
        btnBookaHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookaHotelActionPerformed(evt);
            }
        });
        pnlHead.add(btnBookaHotel);
        btnBookaHotel.setBounds(1250, 30, 90, 30);

        jPanel1.add(pnlHead);
        pnlHead.setBounds(0, 0, 1540, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 1510, 370);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("My Flights");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(10, 140, 1540, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1536, 1536);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LogOutUI logOut = new LogOutUI();
        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBackToSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToSearchActionPerformed
        SearchFlightUI searchFlight = new SearchFlightUI();
        searchFlight.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackToSearchActionPerformed

    private void btnBookaHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookaHotelActionPerformed
        // Prompt the user for booking number
        String bookingNumber = JOptionPane.showInputDialog(this, "Please enter your booking reference:");

        // Check if booking number is not null or empty
        if (bookingNumber != null && !bookingNumber.trim().isEmpty()) {
            try {
                // Check if the booking number exists in flight booking
                if (programManager.isBookingNumberExists(bookingNumber)) {
                    // Check if the booking number exists in hotel booking
                    if (programManager.isHotelBookingExists(bookingNumber)) {
                        // Display a message that a hotel room has already been booked
                        JOptionPane.showMessageDialog(this, "A hotel room has already been booked for this reservation.");
                    } else {
                        // Get flight information
                        DepartureFlight departureFlight = programManager.retrieveFlightBookingInfo(bookingNumber);

                        // Transfer the user to HotelSearchUI with flight information
                        SeparateHotelSearchUI hotelSearch = new SeparateHotelSearchUI(
                                departureFlight.getScheduledFlightDepartureDate(),
                                departureFlight.getArrivalAirportID(),
                                bookingNumber
                        );
                        hotelSearch.setVisible(true);
                        this.dispose();
                    }
                } else {
                    // Display an error message that the booking number does not exist
                    JOptionPane.showMessageDialog(this, "Invalid booking reference. Please check and try again.");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                // Handle the exception as needed
                JOptionPane.showMessageDialog(this, "An error occurred. Please try again later.");
            }
        } else {
            // Display an error message that the booking number is empty
            JOptionPane.showMessageDialog(this, "Please enter a valid booking reference.");
        }

    }//GEN-LAST:event_btnBookaHotelActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingViewUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingViewUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingViewUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingViewUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingViewUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToSearch;
    private javax.swing.JButton btnBookaHotel;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCentral;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JPanel pnlHead;
    // End of variables declaration//GEN-END:variables
}
