/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelcentralflightmanagementsystem;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author the_scs
 */
public class HotelManagementUI extends javax.swing.JFrame {

    private ProgramManager programManager;
    private JComboBox<City> cityComboBox;  // Added for city selection in the same frame

    public HotelManagementUI() {
        programManager = new ProgramManager();
        initComponents();
        
        if (!SessionManager.isLoggedIn()) {
            lblName.setVisible(false);
        } else {
            lblName.setText(SessionManager.getLoggedInUsername());
        }
        
        displayHotelInformation();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblTravel = new javax.swing.JLabel();
        lblCentral = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        lblHotels = new javax.swing.JLabel();
        btnAddHotel = new javax.swing.JButton();
        pnlSide = new javax.swing.JPanel();
        btnFlightManagement = new javax.swing.JButton();
        btnUserManagement = new javax.swing.JButton();
        btnHotelManagement = new javax.swing.JButton();
        btnAirportManagement = new javax.swing.JButton();
        btnAircraftManagement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setPreferredSize(new java.awt.Dimension(1536, 1536));
        pnlMain.setLayout(null);

        pnlHead.setBackground(new java.awt.Color(0, 0, 0));
        pnlHead.setPreferredSize(new java.awt.Dimension(1536, 100));
        pnlHead.setLayout(null);

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlHead.add(btnLogOut);
        btnLogOut.setBounds(1430, 30, 80, 30);

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlHead.add(btnHome);
        btnHome.setBounds(1350, 30, 80, 30);

        lblTravel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblTravel.setForeground(new java.awt.Color(255, 255, 255));
        lblTravel.setText("T R A V E L");
        pnlHead.add(lblTravel);
        lblTravel.setBounds(60, 30, 70, 16);

        lblCentral.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblCentral.setForeground(new java.awt.Color(255, 255, 255));
        lblCentral.setText("C E N T R A L");
        pnlHead.add(lblCentral);
        lblCentral.setBounds(60, 50, 90, 15);

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Full Name");
        pnlHead.add(lblName);
        lblName.setBounds(0, 40, 1540, 16);

        pnlMain.add(pnlHead);
        pnlHead.setBounds(0, 0, 1536, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        pnlMain.add(jScrollPane1);
        jScrollPane1.setBounds(540, 160, 880, 620);

        btnConfirm.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm Changes");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        pnlMain.add(btnConfirm);
        btnConfirm.setBounds(1300, 780, 120, 30);

        lblHotels.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblHotels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHotels.setText("Hotels");
        pnlMain.add(lblHotels);
        lblHotels.setBounds(400, 70, 1140, 120);

        btnAddHotel.setBackground(new java.awt.Color(0, 0, 0));
        btnAddHotel.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHotel.setText("Add a Hotel");
        btnAddHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHotelActionPerformed(evt);
            }
        });
        pnlMain.add(btnAddHotel);
        btnAddHotel.setBounds(540, 780, 120, 30);

        pnlSide.setBackground(new java.awt.Color(0, 0, 0));
        pnlSide.setLayout(null);

        btnFlightManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnFlightManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnFlightManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnFlightManagement.setText("FLIGHT MANAGEMENT");
        btnFlightManagement.setBorderPainted(false);
        btnFlightManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnFlightManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnFlightManagement);
        btnFlightManagement.setBounds(0, 210, 400, 40);

        btnUserManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnUserManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnUserManagement.setText("USER MANAGEMENT");
        btnUserManagement.setBorderPainted(false);
        btnUserManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnUserManagement);
        btnUserManagement.setBounds(0, 250, 400, 40);

        btnHotelManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnHotelManagement.setText("HOTEL MANAGEMENT");
        btnHotelManagement.setBorderPainted(false);
        btnHotelManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnHotelManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnHotelManagement);
        btnHotelManagement.setBounds(0, 290, 400, 40);

        btnAirportManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnAirportManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnAirportManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnAirportManagement.setText("AIRPORT MANAGEMENT");
        btnAirportManagement.setBorderPainted(false);
        btnAirportManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnAirportManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirportManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnAirportManagement);
        btnAirportManagement.setBounds(0, 330, 400, 40);

        btnAircraftManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnAircraftManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnAircraftManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnAircraftManagement.setText("AIRCRAFT MANAGEMENT");
        btnAircraftManagement.setBorderPainted(false);
        btnAircraftManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnAircraftManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAircraftManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnAircraftManagement);
        btnAircraftManagement.setBounds(0, 370, 400, 40);

        pnlMain.add(pnlSide);
        pnlSide.setBounds(0, 80, 400, 1460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        AdminOverviewUI adminOverview = new AdminOverviewUI();
        adminOverview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        updateAndDeleteRecords();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnAddHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHotelActionPerformed
        showAddHotelForm();
    }//GEN-LAST:event_btnAddHotelActionPerformed

    private void btnFlightManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightManagementActionPerformed
        FlightManagementUI flightManagement = new FlightManagementUI();
        flightManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlightManagementActionPerformed

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        UserManagementUI userManagement = new UserManagementUI();
        userManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnHotelManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelManagementActionPerformed
        
    }//GEN-LAST:event_btnHotelManagementActionPerformed

    private void btnAirportManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirportManagementActionPerformed
        AirportManagementUI airportManagement = new AirportManagementUI();
        airportManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAirportManagementActionPerformed

    private void btnAircraftManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAircraftManagementActionPerformed
        AircraftManagementUI aircraftManagement = new AircraftManagementUI();
        aircraftManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAircraftManagementActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LogOutUI logOut = new LogOutUI();

        logOut.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void displayHotelInformation() {
        List<Hotel> hotels = programManager.retrieveHotelInformation();

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 2) {
                    return Integer.class; // Use spinners for the "Number of Rooms" column
                } else if (columnIndex == 4) {
                    return Boolean.class; // Use check boxes for the "Delete" column
                }
                return Object.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1 || column == 2 || column == 4; // Allow editing for Hotel Name, Number of Rooms, and "Delete" columns
            }
        };

        model.addColumn("Hotel ID");
        model.addColumn("Hotel Name");
        model.addColumn("Number of Rooms");
        model.addColumn("City");
        model.addColumn("Delete");

        for (Hotel hotel : hotels) {
            model.addRow(new Object[]{
                hotel.getHotelID(),
                hotel.getHotelName(),
                hotel.getNumRooms(),
                hotel.getCity().getCityName(),
                false
            });
        }

        jTable1.setModel(model);

        // Customize the "Number of Rooms" column to use spinners
        JSpinner spinner = new JSpinner();
        TableColumn roomsColumn = jTable1.getColumnModel().getColumn(2);
        roomsColumn.setCellEditor(new SpinnerEditor(spinner));
        roomsColumn.setCellRenderer(new SpinnerRenderer());
    }

    // Spinner editor
    class SpinnerEditor extends DefaultCellEditor {

        private JSpinner spinner;

        public SpinnerEditor(JSpinner spinner) {
            super(new JTextField());
            this.spinner = spinner;
            editorComponent = spinner;
            setClickCountToStart(1);
            spinner.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        }

        @Override
        public Object getCellEditorValue() {
            return spinner.getValue();
        }
    }

// Spinner renderer
    class SpinnerRenderer extends DefaultTableCellRenderer {

        private JSpinner spinner = new JSpinner();

        public SpinnerRenderer() {
            spinner.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            spinner.setValue(value);
            return spinner;
        }
    }

    private void updateAndDeleteRecords() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowCount = model.getRowCount();
        List<Integer> hotelsToDelete = new ArrayList<>();

        for (int i = 0; i < rowCount; i++) {
            int hotelID = (int) model.getValueAt(i, 0);
            String hotelName = (String) model.getValueAt(i, 1);
            int numRooms;

            try {
                numRooms = Integer.parseInt(model.getValueAt(i, 2).toString()); // Parse as Integer
            } catch (NumberFormatException e) {
                numRooms = 0; // Handle invalid input gracefully
            }

            boolean delete = (boolean) model.getValueAt(i, 4);

            // Update hotel information
            programManager.updateHotelInformation(hotelID, hotelName, numRooms);

            // Check if the hotel should be deleted
            if (delete) {
                hotelsToDelete.add(hotelID);
            }
        }

        // Delete selected hotels
        programManager.deleteSelectedHotels(hotelsToDelete);

        // Refresh the table
        displayHotelInformation();
    }

    private void showAddHotelForm() {
        JFrame addHotelFrame = new JFrame("Add a Hotel");
        addHotelFrame.setSize(300, 200);

        JPanel addHotelPanel = new JPanel();
        addHotelFrame.add(addHotelPanel);

        JTextField hotelNameField = new JTextField(20);
        JSpinner numRoomsSpinner = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1));
        JComboBox<City> cityComboBox = new JComboBox<>();

        // Retrieve cities from the database and populate the combo box
        List<City> cities = programManager.retrieveCities();
        for (City city : cities) {
            cityComboBox.addItem(city);
        }

        JButton addButton = new JButton("Add");
        JButton cancelButton = new JButton("Cancel");

        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get values from the form
                String hotelName = hotelNameField.getText();
                int numRooms = (int) numRoomsSpinner.getValue();
                City selectedCity = (City) cityComboBox.getSelectedItem();

                // Add the hotel
                int newHotelID = programManager.addHotel(hotelName, numRooms, selectedCity.getCityID());

                if (newHotelID != -1) {
                    // Hotel added successfully, update the table
                    displayHotelInformation();
                } else {
                    // Handle failure, show an error message or take appropriate action
                    JOptionPane.showMessageDialog(addHotelFrame, "Failed to add a new hotel.", "Error", JOptionPane.ERROR_MESSAGE);
                }

                addHotelFrame.dispose(); // Close the add hotel form
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addHotelFrame.dispose(); // Close the add hotel form without making changes
            }
        });

        // Add form components to the panel
        addHotelPanel.add(new JLabel("Hotel Name:"));
        addHotelPanel.add(hotelNameField);
        addHotelPanel.add(new JLabel("Number of Rooms:"));
        addHotelPanel.add(numRoomsSpinner);
        addHotelPanel.add(new JLabel("Select City:"));
        addHotelPanel.add(cityComboBox);
        addHotelPanel.add(addButton);
        addHotelPanel.add(cancelButton);

        addHotelFrame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelManagementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHotel;
    private javax.swing.JButton btnAircraftManagement;
    private javax.swing.JButton btnAirportManagement;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnFlightManagement;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHotelManagement;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCentral;
    private javax.swing.JLabel lblHotels;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
