/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelcentralflightmanagementsystem;

/**
 *
 * @author the_scs
 */
public class LoginUI extends javax.swing.JFrame {

    ProgramManager programManager;

    public LoginUI() {
        programManager = new ProgramManager();

        initComponents();
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        btnContactUs = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        lblSlogan = new javax.swing.JLabel();
        lblTravelCentral = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        pfieldPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        pnlLogintxt = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtfieldEmailAddress = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        lblNoAccount = new javax.swing.JLabel();
        lblOr = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        chkShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setPreferredSize(new java.awt.Dimension(1536, 1536));
        pnlMain.setLayout(null);

        pnlHead.setBackground(new java.awt.Color(0, 0, 0));
        pnlHead.setPreferredSize(new java.awt.Dimension(1536, 100));
        pnlHead.setLayout(null);

        btnContactUs.setBackground(new java.awt.Color(0, 0, 0));
        btnContactUs.setForeground(new java.awt.Color(255, 255, 255));
        btnContactUs.setText("Contact Us");
        btnContactUs.setBorder(null);
        pnlHead.add(btnContactUs);
        btnContactUs.setBounds(80, 0, 80, 30);

        btnAboutUs.setBackground(new java.awt.Color(0, 0, 0));
        btnAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btnAboutUs.setText("About Us");
        btnAboutUs.setBorder(null);
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });
        pnlHead.add(btnAboutUs);
        btnAboutUs.setBounds(0, 0, 80, 30);

        lblSlogan.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("Where Travel Meets Simplicity");
        pnlHead.add(lblSlogan);
        lblSlogan.setBounds(800, 180, 290, 28);

        lblTravelCentral.setFont(new java.awt.Font("Perpetua Titling MT", 0, 72)); // NOI18N
        lblTravelCentral.setForeground(new java.awt.Color(255, 255, 255));
        lblTravelCentral.setText("TRAVEL CENTRAL");
        pnlHead.add(lblTravelCentral);
        lblTravelCentral.setBounds(450, 80, 630, 140);

        pnlMain.add(pnlHead);
        pnlHead.setBounds(0, 0, 1536, 260);

        pnlLogin.setBackground(new java.awt.Color(0, 0, 0));
        pnlLogin.setLayout(null);

        pfieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfieldPassword.setPreferredSize(new java.awt.Dimension(300, 45));
        pfieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfieldPasswordActionPerformed(evt);
            }
        });
        pnlLogin.add(pfieldPassword);
        pfieldPassword.setBounds(190, 210, 200, 30);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        pnlLogin.add(lblPassword);
        lblPassword.setBounds(60, 216, 128, 20);

        pnlLogintxt.setLayout(null);

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login");
        pnlLogintxt.add(lblLogin);
        lblLogin.setBounds(20, 10, 149, 32);

        pnlLogin.add(pnlLogintxt);
        pnlLogintxt.setBounds(-20, 40, 170, 50);

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailAddress.setText("Email Address");
        pnlLogin.add(lblEmailAddress);
        lblEmailAddress.setBounds(60, 160, 128, 20);

        txtfieldEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldEmailAddressActionPerformed(evt);
            }
        });
        pnlLogin.add(txtfieldEmailAddress);
        txtfieldEmailAddress.setBounds(190, 150, 200, 30);

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin);
        btnLogin.setBounds(310, 280, 80, 30);

        btnBrowse.setBackground(new java.awt.Color(0, 0, 0));
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setText("Browse");
        btnBrowse.setBorder(null);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        pnlLogin.add(btnBrowse);
        btnBrowse.setBounds(270, 360, 80, 30);

        btnSignUp.setBackground(new java.awt.Color(0, 0, 0));
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.setBorder(null);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        pnlLogin.add(btnSignUp);
        btnSignUp.setBounds(100, 360, 80, 30);

        lblNoAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblNoAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoAccount.setText("Don't have an account?");
        pnlLogin.add(lblNoAccount);
        lblNoAccount.setBounds(160, 320, 130, 16);

        lblOr.setForeground(new java.awt.Color(255, 255, 255));
        lblOr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOr.setText("Or");
        pnlLogin.add(lblOr);
        lblOr.setBounds(210, 360, 30, 30);

        lblError.setForeground(new java.awt.Color(226, 32, 44));
        lblError.setText("Incorrect password or email");
        pnlLogin.add(lblError);
        lblError.setBounds(190, 260, 200, 16);

        chkShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        chkShowPassword.setText("Show Password");
        chkShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPasswordActionPerformed(evt);
            }
        });
        pnlLogin.add(chkShowPassword);
        chkShowPassword.setBounds(290, 240, 120, 20);

        pnlMain.add(pnlLogin);
        pnlLogin.setBounds(540, 280, 450, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void pfieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfieldPasswordActionPerformed

    private void txtfieldEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldEmailAddressActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String email = txtfieldEmailAddress.getText().trim();
        char[] password = pfieldPassword.getPassword();
        String passwordStr = new String(password);

        User user = programManager.getUserByEmailAndPassword(email, passwordStr);
        SessionManager.login(user);

        if (user != null) {
            if (email.endsWith("@travelcentral.co.za")) {
                // Admin login
                AdminOverviewUI adminUI = new AdminOverviewUI();
                adminUI.setVisible(true);
                this.dispose();
            } else {
                // Regular user login
                SearchFlightUI searchUI = new SearchFlightUI();
                searchUI.setVisible(true);
                this.dispose();
            }
        } else {
            lblError.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        SearchFlightUI searchUI = new SearchFlightUI();
        searchUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        // Check if the checkbox is selected
        if (chkShowPassword.isSelected()) {
            // Set the password field to show the plain text
            pfieldPassword.setEchoChar((char) 0);
            chkShowPassword.setText("Hide password");
        } else {
            // Set the password field to hide the password
            pfieldPassword.setEchoChar('*');
            chkShowPassword.setText("Show password");
        }
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        SignUpUI signUp = new SignUpUI();
        signUp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnContactUs;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNoAccount;
    private javax.swing.JLabel lblOr;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblTravelCentral;
    private javax.swing.JPasswordField pfieldPassword;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLogintxt;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtfieldEmailAddress;
    // End of variables declaration//GEN-END:variables
}
