/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelcentralflightmanagementsystem;

import javax.swing.JOptionPane;
/**
 *
 * @author lelet
 */
public class MyBookingsSummary extends javax.swing.JFrame {

    /**
     * Creates new form MyBookingsSummary
     */
    public MyBookingsSummary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonPrivacyPolicy = new javax.swing.JButton();
        jButtonTravellingConditions = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1636, 3164));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HEY Fam! please fill in below to view information about your bookings");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 20, 1138, 48);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Enter your Account details to view your Bookings");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password:");

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));

        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));

        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Booking Order Number:");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Track my Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Booking Order Number?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back to Previous Page to Copy Booking Number");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)
                            .addComponent(jLabel6)
                            .addComponent(jTextField2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(480, 80, 685, 556);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jButtonPrivacyPolicy.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPrivacyPolicy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonPrivacyPolicy.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrivacyPolicy.setText("Privacy policy");
        jButtonPrivacyPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrivacyPolicyActionPerformed(evt);
            }
        });

        jButtonTravellingConditions.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTravellingConditions.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonTravellingConditions.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTravellingConditions.setText("Travelling Conditions");
        jButtonTravellingConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTravellingConditionsActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("About LexFlights");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPrivacyPolicy)
                    .addComponent(jButtonTravellingConditions)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPrivacyPolicy)
                .addGap(18, 18, 18)
                .addComponent(jButtonTravellingConditions)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("About us:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(-4, 740, 1640, 611);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 1590, 740);

        jScrollPane1.setViewportView(jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Bookings for LexFlights");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back to Home");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(505, 505, 505))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrivacyPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrivacyPolicyActionPerformed
        // TODO add your handling code here:
        String answer = "LexFlights Privacy policy:\n"
            + "We are committed to protecting your personal information and your privacy. "
    + "This Privacy Policy outlines how we collect, use, disclose, and safeguard your information when you use our services.\n\n"

    + "1. Collection of Information:\n"
    + "We may collect personal and non-personal information when you use our flight booking services. This information may include your name, contact details, payment information, and flight preferences.\n\n"

    + "2. Use of Information:\n"
    + "We use the collected information to provide and improve our flight booking services. This includes processing bookings, personalizing your experience, and sending relevant updates.\n\n"

    + "3. Disclosure of Information:\n"
    + "We may share your information with our airline partners, payment processors, and service providers to facilitate your flight bookings. Your data may also be disclosed when required by law.\n\n"

    + "4. Data Security:\n"
    + "We take data security seriously and implement measures to protect your information. However, no method of data transmission is entirely secure, and we cannot guarantee absolute security.\n\n"

    + "5. Your Choices:\n"
    + "You have the right to access, update, or delete your personal information. You can also opt out of receiving marketing communications.\n\n"

    + "6. Contact Us:\n"
    + "If you have questions or concerns about our Privacy Policy, please contact us at LexFlights@flightmanagement.com.";


    JOptionPane.showMessageDialog(this, answer, "FAQ: LexFlights Privacy policy", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonPrivacyPolicyActionPerformed

    private void jButtonTravellingConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTravellingConditionsActionPerformed
        // TODO add your handling code here:
        String answer = "LexFlights Travelling conditions:\n"
            + "Before booking your flight, please carefully review the following traveling conditions:\n\n"

    + "1. Booking and Confirmation:\n"
    + "All flight bookings are subject to availability. Once you make a booking, you will receive a confirmation email with your itinerary. Please verify the details for accuracy.\n\n"

    + "2. Cancellations and Changes:\n"
    + "Cancellations and changes to your flight may be subject to fees and policies set by the airline. Please review these policies before making any adjustments to your booking.\n\n"

    + "3. Passport and Visa:\n"
    + "Ensure that your passport is valid for at least six months beyond your travel date. You are responsible for obtaining any required visas or travel permits for your destination.\n\n"

    + "4. Baggage Allowance:\n"
    + "Each airline has specific baggage allowance policies. Please check the baggage limits, fees, and restrictions with the airline you are flying with.\n\n"

    + "5. Flight Check-In:\n"
    + "Arrive at the airport well in advance of your flight's departure time to allow for check-in and security procedures. Most airlines offer online check-in options.\n\n"

    + "6. Flight Delays and Cancellations:\n"
    + "Flight schedules are subject to change due to various factors. In the event of delays or cancellations, the airline will provide assistance and information as per their policies.\n\n"

    + "7. Travel Insurance:\n"
    + "Consider purchasing travel insurance to protect against unexpected events such as trip cancellations, medical emergencies, or lost luggage.\n\n"

    + "8. Health and Safety:\n"
    + "Follow all health and safety guidelines at the airport and during your flight. Your safety is our top priority.\n\n"

    + "9. Travel Documents:\n"
    + "Carry all required travel documents, including your passport, visa, tickets, and any necessary identification.\n\n"

    + "10. Enjoy Your Journey:\n"
    + "We wish you a pleasant and enjoyable journey! If you have any questions or need assistance during your travels, please don't hesitate to reach out to our support team.\n\n";


    JOptionPane.showMessageDialog(this, answer, "FAQ: LexFlights Travelling conditions", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonTravellingConditionsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String answer = "About LexFlights :\n"
            + "Before booking your flight, please carefully review the following traveling conditions:\n\n"

     + "Welcome to Lex's Best Incredible Flights!\n\n"

    + "At Lex's Best Incredible Flights, we are passionate about providing you with exceptional travel experiences. Our mission is to make your journey not just a trip but a memorable adventure.\n\n"

    + "Our Commitment:\n"
    + "1. **Exceptional Service:** We are dedicated to offering outstanding customer service at every step of your travel journey. Our team is here to assist you with booking flights, hotels, car rentals, and more.\n\n"

    + "2. **Wide Selection:** With access to a vast network of airlines and travel partners, we can offer you a wide range of flight options, destinations, and travel packages to suit your needs and preferences.\n\n"

    + "3. **Competitive Prices:** We understand the value of your hard-earned money. That's why we work tirelessly to bring you the best deals and competitive prices, ensuring you get the most out of your travel budget.\n\n"

    + "4. **Travel Expertise:** Our team consists of travel experts who are well-versed in the travel industry. We stay up-to-date with the latest travel trends and provide you with valuable insights and recommendations.\n\n"

    + "5. **Your Travel Partner:** Whether you're planning a family vacation, a business trip, or a solo adventure, we're here to be your trusted travel partner. We take care of the details, so you can focus on creating lasting memories.\n\n"

    + "Contact Us:\n"
    + "We're here to assist you 24/7. If you have any questions, need travel advice, or require assistance with your bookings, please don't hesitate to contact our customer support team.\n\n"

    + "Thank you for choosing Lex's Best Incredible Flights for your travel needs. We look forward to helping you explore the world and create unforgettable moments.\n\n";


    JOptionPane.showMessageDialog(this, answer, "FAQ: About LexFlights ", JOptionPane.INFORMATION_MESSAGE);
        

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SearchFlightUI mainFrame = new SearchFlightUI();
    
    // Set the visibility of the SearchFlightUI frame
    mainFrame.setVisible(true);

    // Close the current frame (assuming this is in AvailableFlightsSearch)
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserFlightBookingReciept mainFrame = new UserFlightBookingReciept();
    
    // Set the visibility of the SearchFlightUI frame
    mainFrame.setVisible(true);

    // Close the current frame (assuming this is in AvailableFlightsSearch)
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String answer = "Tracking your booking :\n"
            + "To Track your booking you must:\n\n"

     

    
    + "1. Book a Flight after searching for Flight.\n\n"

    + "2. Copy gnerated Booking Order Number from same window of Booked Flight.\n\n"

    + "3. Proceed to My Bookings having your Copied Booking Order Number.\n\n"

    + "4. Paste the Booking Order Number in the required field the Track your Booking, having your booking Fullname and Email entered as well.\n\n"

    
    + "Contact Us @ 0635371084:\n"
    + "We're here to assist you 24/7. If you have any questions, need travel advice, or require assistance with your bookings, please don't hesitate to contact our customer support team.\n\n"

    + "Thank you for choosing Lex's Best Incredible Flights for your travel needs. We look forward to helping you explore the world and create unforgettable moments.\n\n";


    JOptionPane.showMessageDialog(this, answer, "FAQ: About LexFlights ", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AvailableFlightsSearch mainFrame = new AvailableFlightsSearch();
    
    // Set the visibility of the SearchFlightUI frame
    mainFrame.setVisible(true);

    // Close the current frame (assuming this is in AvailableFlightsSearch)
    this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBookingsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBookingsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBookingsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBookingsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBookingsSummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonPrivacyPolicy;
    private javax.swing.JButton jButtonTravellingConditions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
