/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelcentralflightmanagementsystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author okhum
 */
public class SeparateHotelBookingUI extends javax.swing.JFrame {

    private String checkInDate;
    private String checkOutDate;
    private boolean meals;
    private float hotelCost;
    private int numNights;
    private float mealCost;
    private String bookingNumber;
    private int arrivalAirportID;
    private int userID;
    ProgramManager programManager;
    
    public SeparateHotelBookingUI(String checkInDate, String checkOutDate, boolean meals, float hotelCost, int numNights, float mealCost, String bookingNumber, int arrivalAirportID) {
        this.checkInDate = checkInDate;
        this.checkOutDate = checkOutDate;
        this.meals = meals;
        this.hotelCost = hotelCost;
        this.numNights = numNights;
        this.bookingNumber = bookingNumber;
        this.arrivalAirportID = arrivalAirportID;
        programManager = new ProgramManager();
        
        initComponents();
        
        if (!SessionManager.isLoggedIn()) {
            lblName.setVisible(false);
            btnLogOut.setVisible(false);
        } else {
            lblName.setText(SessionManager.getLoggedInUsername());
        }
        
        populateDetails();
        
        userID = SessionManager.getLoggedInUser().getUserID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetails = new javax.swing.JPanel();
        lblPaymentDetails = new javax.swing.JLabel();
        pnlPaymentDetails = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblCardDetails = new javax.swing.JLabel();
        lblBillingAddressLine = new javax.swing.JLabel();
        lblCardNumber = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        lblCVC = new javax.swing.JLabel();
        lblCardOwner = new javax.swing.JLabel();
        txtfieldCardNumber = new javax.swing.JTextField();
        txtfieldCVC = new javax.swing.JTextField();
        txtfieldCardOwner = new javax.swing.JTextField();
        lblBillingAddress = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblPostalCode = new javax.swing.JLabel();
        lblStreetName = new javax.swing.JLabel();
        lblTown = new javax.swing.JLabel();
        lblResidenceNumber = new javax.swing.JLabel();
        txtfieldCountry = new javax.swing.JTextField();
        txtfieldPostalCode = new javax.swing.JTextField();
        txtfieldStreetName = new javax.swing.JTextField();
        txtfieldTown = new javax.swing.JTextField();
        txtfieldResidenceBumber = new javax.swing.JTextField();
        chkboxTsnCs = new javax.swing.JCheckBox();
        btnPay = new javax.swing.JButton();
        lblCardDetailsLine = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        rbtnVisa = new javax.swing.JRadioButton();
        rbtnMasterCard = new javax.swing.JRadioButton();
        lblPaymentMethod = new javax.swing.JLabel();
        pnlHotelDetails = new javax.swing.JPanel();
        lblDepartureFlight1 = new javax.swing.JLabel();
        lblHotelName = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        lblDays = new javax.swing.JLabel();
        lblHotelStayR = new javax.swing.JLabel();
        lblHotelStayTotal = new javax.swing.JLabel();
        lblMeals = new javax.swing.JLabel();
        lblMealsR = new javax.swing.JLabel();
        lblMealsTotal = new javax.swing.JLabel();
        pnlTotal = new javax.swing.JPanel();
        lblTotalDue = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnProceedToPayment = new javax.swing.JButton();
        lblHotelDetails = new javax.swing.JLabel();
        pnlHead = new javax.swing.JPanel();
        lblInstruction = new javax.swing.JLabel();
        lblTravel = new javax.swing.JLabel();
        lblCentral = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnBackToSearch = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetails.setPreferredSize(new java.awt.Dimension(1499901, 1599964));
        pnlDetails.setLayout(null);

        lblPaymentDetails.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPaymentDetails.setText("Payment Details");
        pnlDetails.add(lblPaymentDetails);
        lblPaymentDetails.setBounds(210, 490, 290, 50);

        pnlPaymentDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlPaymentDetails.setMaximumSize(new java.awt.Dimension(32767, 32769));
        pnlPaymentDetails.setPreferredSize(new java.awt.Dimension(930, 7910));
        pnlPaymentDetails.setLayout(null);
        pnlPaymentDetails.add(jLabel20);
        jLabel20.setBounds(705, 12, 0, 93);

        lblCardDetails.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCardDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCardDetails.setText("Card Details:");
        pnlPaymentDetails.add(lblCardDetails);
        lblCardDetails.setBounds(0, 30, 950, 38);

        lblBillingAddressLine.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBillingAddressLine.setText("------------------------------------------------------------------------------------------------");
        pnlPaymentDetails.add(lblBillingAddressLine);
        lblBillingAddressLine.setBounds(7, 330, 940, 11);

        lblCardNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCardNumber.setText("Card Number: *");
        pnlPaymentDetails.add(lblCardNumber);
        lblCardNumber.setBounds(290, 110, 140, 28);

        lblExpirationDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExpirationDate.setText("Expiration Date: *");
        pnlPaymentDetails.add(lblExpirationDate);
        lblExpirationDate.setBounds(290, 150, 150, 28);

        lblCVC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCVC.setText("CVC: *");
        pnlPaymentDetails.add(lblCVC);
        lblCVC.setBounds(290, 190, 60, 28);

        lblCardOwner.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCardOwner.setText("Card Owner's Name: *");
        pnlPaymentDetails.add(lblCardOwner);
        lblCardOwner.setBounds(290, 230, 190, 28);

        txtfieldCardNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldCardNumber);
        txtfieldCardNumber.setBounds(520, 110, 301, 26);

        txtfieldCVC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldCVC);
        txtfieldCVC.setBounds(520, 190, 301, 26);

        txtfieldCardOwner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldCardOwner);
        txtfieldCardOwner.setBounds(520, 230, 301, 26);

        lblBillingAddress.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBillingAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBillingAddress.setText("Billing Address (Card Owner):");
        pnlPaymentDetails.add(lblBillingAddress);
        lblBillingAddress.setBounds(0, 290, 950, 33);

        lblCountry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCountry.setText("Country: *");
        pnlPaymentDetails.add(lblCountry);
        lblCountry.setBounds(290, 480, 90, 28);

        lblPostalCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPostalCode.setText("Postal Code: *");
        pnlPaymentDetails.add(lblPostalCode);
        lblPostalCode.setBounds(290, 520, 120, 28);

        lblStreetName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStreetName.setText("Street: *");
        pnlPaymentDetails.add(lblStreetName);
        lblStreetName.setBounds(290, 400, 70, 28);

        lblTown.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTown.setText("Town: *");
        pnlPaymentDetails.add(lblTown);
        lblTown.setBounds(290, 440, 70, 28);

        lblResidenceNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResidenceNumber.setText("Residence Number: *");
        pnlPaymentDetails.add(lblResidenceNumber);
        lblResidenceNumber.setBounds(290, 360, 180, 28);

        txtfieldCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldCountry);
        txtfieldCountry.setBounds(530, 480, 301, 26);

        txtfieldPostalCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldPostalCode);
        txtfieldPostalCode.setBounds(530, 520, 301, 26);

        txtfieldStreetName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldStreetName);
        txtfieldStreetName.setBounds(530, 400, 301, 26);

        txtfieldTown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldTown);
        txtfieldTown.setBounds(530, 440, 301, 26);

        txtfieldResidenceBumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(txtfieldResidenceBumber);
        txtfieldResidenceBumber.setBounds(530, 360, 301, 26);

        chkboxTsnCs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkboxTsnCs.setText("I have read and accept: Conditions of Carriage Booking Conditions (including cancellation and refund policy) Terms and Conditions.");
        chkboxTsnCs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkboxTsnCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxTsnCsActionPerformed(evt);
            }
        });
        pnlPaymentDetails.add(chkboxTsnCs);
        chkboxTsnCs.setBounds(10, 570, 918, 24);

        btnPay.setBackground(new java.awt.Color(0, 0, 0));
        btnPay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Book and Pay Flight");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        pnlPaymentDetails.add(btnPay);
        btnPay.setBounds(690, 600, 242, 39);

        lblCardDetailsLine.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCardDetailsLine.setText("------------------------------------------------------------------------------------------------");
        pnlPaymentDetails.add(lblCardDetailsLine);
        lblCardDetailsLine.setBounds(7, 70, 940, 11);

        jMonthChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlPaymentDetails.add(jMonthChooser1);
        jMonthChooser1.setBounds(520, 150, 130, 22);
        pnlPaymentDetails.add(jYearChooser1);
        jYearChooser1.setBounds(650, 150, 64, 22);

        pnlDetails.add(pnlPaymentDetails);
        pnlPaymentDetails.setBounds(290, 650, 950, 670);

        rbtnVisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnVisa.setText("VISA");
        rbtnVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVisaActionPerformed(evt);
            }
        });
        pnlDetails.add(rbtnVisa);
        rbtnVisa.setBounds(290, 620, 70, 25);

        rbtnMasterCard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnMasterCard.setText("MasterCard");
        rbtnMasterCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMasterCardActionPerformed(evt);
            }
        });
        pnlDetails.add(rbtnMasterCard);
        rbtnMasterCard.setBounds(450, 620, 110, 25);

        lblPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaymentMethod.setText("Choose your payment method");
        pnlDetails.add(lblPaymentMethod);
        lblPaymentMethod.setBounds(210, 540, 260, 25);

        pnlHotelDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlHotelDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        pnlHotelDetails.setPreferredSize(new java.awt.Dimension(560, 254));
        pnlHotelDetails.setLayout(null);

        lblDepartureFlight1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDepartureFlight1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDepartureFlight1.setText("Hotel Stay Details");
        pnlHotelDetails.add(lblDepartureFlight1);
        lblDepartureFlight1.setBounds(10, 50, 544, 40);

        lblHotelName.setText("Hotel Name");
        pnlHotelDetails.add(lblHotelName);
        lblHotelName.setBounds(10, 100, 250, 16);

        lblRoomType.setText("Room Type");
        pnlHotelDetails.add(lblRoomType);
        lblRoomType.setBounds(10, 120, 260, 16);

        lblDays.setText("0 Night(s)");
        pnlHotelDetails.add(lblDays);
        lblDays.setBounds(10, 140, 160, 16);

        lblHotelStayR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHotelStayR.setText("R");
        pnlHotelDetails.add(lblHotelStayR);
        lblHotelStayR.setBounds(420, 160, 37, 16);

        lblHotelStayTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHotelStayTotal.setText("0000.00");
        pnlHotelDetails.add(lblHotelStayTotal);
        lblHotelStayTotal.setBounds(470, 160, 80, 16);

        lblMeals.setText("Meal(s)");
        pnlHotelDetails.add(lblMeals);
        lblMeals.setBounds(10, 180, 50, 16);

        lblMealsR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMealsR.setText("R");
        pnlHotelDetails.add(lblMealsR);
        lblMealsR.setBounds(420, 200, 40, 16);

        lblMealsTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMealsTotal.setText("0000.00");
        pnlHotelDetails.add(lblMealsTotal);
        lblMealsTotal.setBounds(470, 200, 80, 16);

        pnlDetails.add(pnlHotelDetails);
        pnlHotelDetails.setBounds(480, 80, 560, 270);

        pnlTotal.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalDue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalDue.setText("Total Due: R");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("0000.00");

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalDue, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDue)
                    .addComponent(lblTotal))
                .addGap(21, 21, 21))
        );

        pnlDetails.add(pnlTotal);
        pnlTotal.setBounds(650, 360, 260, 40);

        btnProceedToPayment.setBackground(new java.awt.Color(0, 0, 0));
        btnProceedToPayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProceedToPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnProceedToPayment.setText("Proceed to Payment");
        btnProceedToPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedToPaymentActionPerformed(evt);
            }
        });
        pnlDetails.add(btnProceedToPayment);
        btnProceedToPayment.setBounds(650, 410, 200, 50);

        lblHotelDetails.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblHotelDetails.setText("Hotel Details");
        pnlDetails.add(lblHotelDetails);
        lblHotelDetails.setBounds(480, 30, 212, 48);

        getContentPane().add(pnlDetails);
        pnlDetails.setBounds(0, 130, 1499901, 1599964);

        pnlHead.setBackground(new java.awt.Color(0, 0, 0));

        lblInstruction.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblInstruction.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruction.setText("Review your Flight and Hotel Details");

        lblTravel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblTravel.setForeground(new java.awt.Color(255, 255, 255));
        lblTravel.setText("T R A V E L");

        lblCentral.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblCentral.setForeground(new java.awt.Color(255, 255, 255));
        lblCentral.setText("C E N T R A L");

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Full Name");

        btnBackToSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnBackToSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToSearch.setText("Back To Search");
        btnBackToSearch.setBorder(null);
        btnBackToSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToSearchActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1548, Short.MAX_VALUE)
            .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHeadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlHeadLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1200, 1200, 1200)
                            .addComponent(btnBackToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 1530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 1530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHeadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlHeadLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(lblTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(lblCentral))
                        .addComponent(btnBackToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlHeadLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(lblInstruction)))
                    .addGap(5, 5, 5)
                    .addComponent(lblName)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlHead);
        pnlHead.setBounds(0, 0, 1548, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkboxTsnCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxTsnCsActionPerformed
        if (chkboxTsnCs.isSelected()) {
            btnPay.setEnabled(true);
        } else {
            btnPay.setEnabled(false);
        }
    }//GEN-LAST:event_chkboxTsnCsActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed

        int hotelID = programManager.retrieveHotelIDByCityID(programManager.retrieveCityID(programManager.retrieveCityName(arrivalAirportID)));

        // Call the method to add flight and hotel booking
        
        programManager.addHotelBooking(bookingNumber, checkInDate, checkOutDate, hotelCost, "Confirmed", userID, hotelID);

        HotelBookingConfirmationUI mainFrame = new HotelBookingConfirmationUI(bookingNumber);

        // Set the visibility of the SearchFlightUI frame
        mainFrame.setVisible(true);

        // Close the current frame (assuming this is in AvailableFlightsSearch)
        this.dispose();
    }//GEN-LAST:event_btnPayActionPerformed

    private void rbtnVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVisaActionPerformed
        if (rbtnVisa.isSelected()) {
            txtfieldCardNumber.setText("4917484589897107");
            jMonthChooser1.setMonth(1);
            jYearChooser1.setYear(2026);
            txtfieldCVC.setText("548");
        } else if (rbtnMasterCard.isSelected()) {
            txtfieldCardNumber.setText("5425233430109903");
            jMonthChooser1.setMonth(8);
            jYearChooser1.setYear(2025);
            txtfieldCVC.setText("764");
        }
    }//GEN-LAST:event_rbtnVisaActionPerformed

    private void rbtnMasterCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMasterCardActionPerformed
        if (rbtnVisa.isSelected()) {
            txtfieldCardNumber.setText("4917484589897107");
            jMonthChooser1.setMonth(1);
            jYearChooser1.setYear(2026);
            txtfieldCVC.setText("548");
        } else if (rbtnMasterCard.isSelected()) {
            txtfieldCardNumber.setText("5425233430109903");
            jMonthChooser1.setMonth(8);
            jYearChooser1.setYear(2025);
            txtfieldCVC.setText("764");
        }
    }//GEN-LAST:event_rbtnMasterCardActionPerformed

    private void btnProceedToPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedToPaymentActionPerformed
        btnProceedToPayment.setVisible(false);

        lblPaymentDetails.setVisible(true);
        lblPaymentMethod.setVisible(true);

        rbtnVisa.setVisible(true);
        rbtnMasterCard.setVisible(true);
        pnlPaymentDetails.setVisible(true);

        pnlPaymentDetails.setVisible(true);

    }//GEN-LAST:event_btnProceedToPaymentActionPerformed

    private void btnBackToSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToSearchActionPerformed
        HotelListingUI mainFrame;
        try {
            mainFrame = new HotelListingUI();
            // Set the visibility of the HotelListingUI frame
            mainFrame.setVisible(true);
            // Close the current frame
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(HotelBookingUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackToSearchActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LogOutUI logOut = new LogOutUI();

        logOut.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void populateDetails() {
        
        lblHotelStayTotal.setText(Float.toString(hotelCost));
        
        lblDays.setText(Integer.toString(numNights));
        
        lblMealsTotal.setText(Float.toString(mealCost));

        lblTotal.setText(Float.toString(hotelCost + mealCost));
        
        if (!SessionManager.isLoggedIn()) {
            txtfieldCardOwner.setText("User User");
        } else {
            txtfieldCardOwner.setText(SessionManager.getLoggedInUsername());
        }

        txtfieldResidenceBumber.setText("12");
        txtfieldStreetName.setText("Cowley Avenue");
        txtfieldTown.setText("Cape Town");
        txtfieldCountry.setText("South Africa");
        txtfieldPostalCode.setText("8001");

        if (chkboxTsnCs.isSelected()) {
            btnPay.setEnabled(true);
        } else {
            btnPay.setEnabled(false);
        }

        if (!SessionManager.isLoggedIn()) {
            lblName.setVisible(false);
            btnLogOut.setVisible(false);
        } else {
            lblName.setText(SessionManager.getLoggedInUsername());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeparateHotelBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeparateHotelBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeparateHotelBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeparateHotelBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SeparateHotelBookingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToSearch;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnProceedToPayment;
    private javax.swing.JCheckBox chkboxTsnCs;
    private javax.swing.JLabel jLabel20;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lblBillingAddress;
    private javax.swing.JLabel lblBillingAddressLine;
    private javax.swing.JLabel lblCVC;
    private javax.swing.JLabel lblCardDetails;
    private javax.swing.JLabel lblCardDetailsLine;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblCardOwner;
    private javax.swing.JLabel lblCentral;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDays;
    private javax.swing.JLabel lblDepartureFlight1;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblHotelDetails;
    private javax.swing.JLabel lblHotelName;
    private javax.swing.JLabel lblHotelStayR;
    private javax.swing.JLabel lblHotelStayTotal;
    private javax.swing.JLabel lblInstruction;
    private javax.swing.JLabel lblMeals;
    private javax.swing.JLabel lblMealsR;
    private javax.swing.JLabel lblMealsTotal;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPaymentDetails;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblResidenceNumber;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDue;
    private javax.swing.JLabel lblTown;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlHotelDetails;
    private javax.swing.JPanel pnlPaymentDetails;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JRadioButton rbtnMasterCard;
    private javax.swing.JRadioButton rbtnVisa;
    private javax.swing.JTextField txtfieldCVC;
    private javax.swing.JTextField txtfieldCardNumber;
    private javax.swing.JTextField txtfieldCardOwner;
    private javax.swing.JTextField txtfieldCountry;
    private javax.swing.JTextField txtfieldPostalCode;
    private javax.swing.JTextField txtfieldResidenceBumber;
    private javax.swing.JTextField txtfieldStreetName;
    private javax.swing.JTextField txtfieldTown;
    // End of variables declaration//GEN-END:variables
}
