/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelcentralflightmanagementsystem;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import travelcentralflightmanagementsystem.User.UserStatus;

/**
 *
 * @author the_scs
 */
public class SignUpUI extends javax.swing.JFrame {

    ProgramManager programManager;

    public SignUpUI() {
        programManager = new ProgramManager();

        initComponents();

        lblPasswordError.setVisible(false);
        lblEmailError.setVisible(false);
        lblFirstNameError.setVisible(false);
        lblLastNameError.setVisible(false);
        lblPhoneNumberError.setVisible(false);

        // Define common retrieval questions
        String[] commonQuestions = {
            "What is your mother's maiden name?",
            "In what city were you born?",
            "What is the name of your first pet?",
            "What is the make and model of your first car?",
            "What is your favorite color?", // Add more questions as needed
        };

// Populate the combo box with common retrieval questions
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(commonQuestions);
        cmbRetrievalQuestion.setModel(model);

        SpinnerModel ageModel = new SpinnerNumberModel(0, 0, 150, 1);
        spnAge.setModel(ageModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        btnContactUs = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        lblTravel = new javax.swing.JLabel();
        lblCentral = new javax.swing.JLabel();
        btnAboutUs = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblHotels = new javax.swing.JLabel();
        pnlSignUp = new javax.swing.JPanel();
        pfieldPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtfieldEmailAddress = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        lblPasswordError = new javax.swing.JLabel();
        chkShowPassword = new javax.swing.JCheckBox();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtfieldLastName = new javax.swing.JTextField();
        txtfieldFirstName = new javax.swing.JTextField();
        pfieldConfirmPassword = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        spnAge = new javax.swing.JSpinner();
        lblRetrievalQuestion = new javax.swing.JLabel();
        cmbRetrievalQuestion = new javax.swing.JComboBox<>();
        lblAnswer = new javax.swing.JLabel();
        txtfieldAnswer = new javax.swing.JTextField();
        lblEmailError = new javax.swing.JLabel();
        lblLastNameError = new javax.swing.JLabel();
        lblFirstNameError = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtfieldPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumberError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1536, 1536));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setPreferredSize(new java.awt.Dimension(1536, 1536));
        pnlMain.setLayout(null);

        pnlHead.setBackground(new java.awt.Color(0, 0, 0));
        pnlHead.setPreferredSize(new java.awt.Dimension(1536, 100));
        pnlHead.setLayout(null);

        btnContactUs.setBackground(new java.awt.Color(0, 0, 0));
        btnContactUs.setForeground(new java.awt.Color(255, 255, 255));
        btnContactUs.setText("Contact Us");
        btnContactUs.setBorder(null);
        pnlHead.add(btnContactUs);
        btnContactUs.setBounds(1430, 30, 80, 30);

        btnBrowse.setBackground(new java.awt.Color(0, 0, 0));
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setText("Browse");
        btnBrowse.setBorder(null);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        pnlHead.add(btnBrowse);
        btnBrowse.setBounds(1270, 30, 80, 30);

        lblTravel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblTravel.setForeground(new java.awt.Color(255, 255, 255));
        lblTravel.setText("T R A V E L");
        pnlHead.add(lblTravel);
        lblTravel.setBounds(60, 30, 70, 16);

        lblCentral.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblCentral.setForeground(new java.awt.Color(255, 255, 255));
        lblCentral.setText("C E N T R A L");
        pnlHead.add(lblCentral);
        lblCentral.setBounds(60, 50, 90, 15);

        btnAboutUs.setBackground(new java.awt.Color(0, 0, 0));
        btnAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btnAboutUs.setText("About Us");
        btnAboutUs.setBorder(null);
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });
        pnlHead.add(btnAboutUs);
        btnAboutUs.setBounds(1350, 30, 80, 30);

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlHead.add(btnLogin);
        btnLogin.setBounds(1190, 30, 80, 30);

        pnlMain.add(pnlHead);
        pnlHead.setBounds(0, 0, 1536, 80);

        lblHotels.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblHotels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHotels.setText("Let's Get You Registered");
        pnlMain.add(lblHotels);
        lblHotels.setBounds(0, 70, 1540, 120);

        pnlSignUp.setBackground(new java.awt.Color(0, 0, 0));
        pnlSignUp.setLayout(null);

        pfieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfieldPassword.setPreferredSize(new java.awt.Dimension(300, 45));
        pnlSignUp.add(pfieldPassword);
        pfieldPassword.setBounds(340, 280, 200, 30);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password");
        pnlSignUp.add(lblPassword);
        lblPassword.setBounds(140, 280, 128, 30);

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmailAddress.setText("Email Address");
        pnlSignUp.add(lblEmailAddress);
        lblEmailAddress.setBounds(140, 180, 128, 30);
        pnlSignUp.add(txtfieldEmailAddress);
        txtfieldEmailAddress.setBounds(340, 180, 200, 30);

        btnSignUp.setBackground(new java.awt.Color(0, 0, 0));
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.setBorder(null);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        pnlSignUp.add(btnSignUp);
        btnSignUp.setBounds(490, 580, 80, 30);

        lblPasswordError.setForeground(new java.awt.Color(226, 32, 44));
        lblPasswordError.setText("Passwords do not match");
        pnlSignUp.add(lblPasswordError);
        lblPasswordError.setBounds(410, 370, 200, 16);

        chkShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        chkShowPassword.setText("Show Password");
        chkShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPasswordActionPerformed(evt);
            }
        });
        pnlSignUp.add(chkShowPassword);
        chkShowPassword.setBounds(440, 310, 120, 20);

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstName.setText("First Name");
        pnlSignUp.add(lblFirstName);
        lblFirstName.setBounds(140, 60, 128, 30);

        lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLastName.setText("Last Name");
        pnlSignUp.add(lblLastName);
        lblLastName.setBounds(140, 120, 130, 30);
        pnlSignUp.add(txtfieldLastName);
        txtfieldLastName.setBounds(340, 120, 200, 30);
        pnlSignUp.add(txtfieldFirstName);
        txtfieldFirstName.setBounds(340, 60, 200, 30);

        pfieldConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfieldConfirmPassword.setPreferredSize(new java.awt.Dimension(300, 45));
        pnlSignUp.add(pfieldConfirmPassword);
        pfieldConfirmPassword.setBounds(340, 340, 200, 30);

        lblConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConfirmPassword.setText("Confirm Password");
        pnlSignUp.add(lblConfirmPassword);
        lblConfirmPassword.setBounds(90, 340, 180, 30);

        lblAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age");
        pnlSignUp.add(lblAge);
        lblAge.setBounds(140, 400, 128, 30);
        pnlSignUp.add(spnAge);
        spnAge.setBounds(340, 400, 70, 30);

        lblRetrievalQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRetrievalQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lblRetrievalQuestion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRetrievalQuestion.setText("Account Retrieval Question");
        pnlSignUp.add(lblRetrievalQuestion);
        lblRetrievalQuestion.setBounds(40, 470, 230, 30);

        cmbRetrievalQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlSignUp.add(cmbRetrievalQuestion);
        cmbRetrievalQuestion.setBounds(340, 470, 190, 30);

        lblAnswer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(255, 255, 255));
        lblAnswer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAnswer.setText("Answer");
        pnlSignUp.add(lblAnswer);
        lblAnswer.setBounds(40, 530, 230, 30);
        pnlSignUp.add(txtfieldAnswer);
        txtfieldAnswer.setBounds(340, 530, 200, 30);

        lblEmailError.setForeground(new java.awt.Color(226, 32, 44));
        lblEmailError.setText("Invalid email address");
        pnlSignUp.add(lblEmailError);
        lblEmailError.setBounds(430, 210, 200, 16);

        lblLastNameError.setForeground(new java.awt.Color(226, 32, 44));
        lblLastNameError.setText("Invalid last name");
        pnlSignUp.add(lblLastNameError);
        lblLastNameError.setBounds(450, 150, 200, 16);

        lblFirstNameError.setForeground(new java.awt.Color(226, 32, 44));
        lblFirstNameError.setText("Invalid first name");
        pnlSignUp.add(lblFirstNameError);
        lblFirstNameError.setBounds(450, 90, 200, 16);

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhoneNumber.setText("Phone Number");
        pnlSignUp.add(lblPhoneNumber);
        lblPhoneNumber.setBounds(140, 230, 128, 30);
        pnlSignUp.add(txtfieldPhoneNumber);
        txtfieldPhoneNumber.setBounds(340, 230, 200, 30);

        lblPhoneNumberError.setForeground(new java.awt.Color(226, 32, 44));
        lblPhoneNumberError.setText("Invalid phone number");
        pnlSignUp.add(lblPhoneNumberError);
        lblPhoneNumberError.setBounds(430, 260, 200, 16);

        pnlMain.add(pnlSignUp);
        pnlSignUp.setBounds(470, 200, 600, 630);

        getContentPane().add(pnlMain);
        pnlMain.setBounds(0, 0, 1536, 1536);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        SearchFlightUI searchUI = new SearchFlightUI();
        searchUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        LoginUI login = new LoginUI();

        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // Reset error labels
        lblPasswordError.setVisible(false);
        lblEmailError.setVisible(false);
        lblFirstNameError.setVisible(false);
        lblLastNameError.setVisible(false);
        lblPhoneNumberError.setVisible(false);

        // Get values from the input fields
        String firstName = txtfieldFirstName.getText().trim();
        String lastName = txtfieldLastName.getText().trim();
        String emailAddress = txtfieldEmailAddress.getText().trim();
        String password = new String(pfieldPassword.getPassword());
        String confirmPassword = new String(pfieldConfirmPassword.getPassword());
        int age = (int) spnAge.getValue();
        String retrievalQuestion = (String) cmbRetrievalQuestion.getSelectedItem();
        String retrievalAnswer = txtfieldAnswer.getText().trim();
        String phoneNumber = txtfieldPhoneNumber.getText().trim();

        // Validate input fields
        boolean isValid = true;

        if (firstName.isEmpty() || !firstName.matches("[a-zA-Z]+")) {
            lblFirstNameError.setVisible(true);
            isValid = false;
        }

        if (lastName.isEmpty() || !lastName.matches("[a-zA-Z]+")) {
            lblLastNameError.setVisible(true);
            isValid = false;
        }

        if (emailAddress.isEmpty() || !emailAddress.contains("@") || !emailAddress.contains(".")) {
            lblEmailError.setVisible(true);
            isValid = false;
        }

        if (password.isEmpty() || !password.equals(confirmPassword)) {
            lblPasswordError.setVisible(true);
            isValid = false;
        }

        if (!phoneNumber.matches("\\d{10}")) {
            lblPhoneNumberError.setVisible(true);
            isValid = false;
        }

        // Additional validations...
        if (isValid) {
            
            // Perform sign-up
            programManager.signUp(firstName, lastName, emailAddress, phoneNumber, age, password, UserStatus.ACTIVE, retrievalQuestion, retrievalAnswer);

            // Show success message
            JOptionPane.showMessageDialog(this, "Sign-up successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear input fields
            txtfieldFirstName.setText("");
            txtfieldLastName.setText("");
            txtfieldEmailAddress.setText("");
            txtfieldPhoneNumber.setText("");
            pfieldPassword.setText("");
            pfieldConfirmPassword.setText("");
            spnAge.setValue(0); // Or the default value
            cmbRetrievalQuestion.setSelectedIndex(0); // Or the default index
            txtfieldAnswer.setText("");
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        // Check if the checkbox is selected
        if (chkShowPassword.isSelected()) {
            // Set the password field to show the plain text
            pfieldPassword.setEchoChar((char) 0);
            chkShowPassword.setText("Hide password");
        } else {
            // Set the password field to hide the password
            pfieldPassword.setEchoChar('*');
            chkShowPassword.setText("Show password");
        }
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnContactUs;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JComboBox<String> cmbRetrievalQuestion;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblCentral;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstNameError;
    private javax.swing.JLabel lblHotels;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastNameError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberError;
    private javax.swing.JLabel lblRetrievalQuestion;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JPasswordField pfieldConfirmPassword;
    private javax.swing.JPasswordField pfieldPassword;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSignUp;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextField txtfieldAnswer;
    private javax.swing.JTextField txtfieldEmailAddress;
    private javax.swing.JTextField txtfieldFirstName;
    private javax.swing.JTextField txtfieldLastName;
    private javax.swing.JTextField txtfieldPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
