/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelcentralflightmanagementsystem;

import java.awt.Component;
import java.util.EventObject;
import java.util.List;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import travelcentralflightmanagementsystem.User.UserStatus;

/**
 *
 * @author the_scs
 */
public class UserManagementUI extends javax.swing.JFrame {

    private ProgramManager programManager;
    private String selectedStatus;

    private class StatusCellEditor extends AbstractCellEditor implements TableCellEditor {

        private JComboBox<String> comboBox;

        public StatusCellEditor(String[] items) {
            this.comboBox = new JComboBox<>(items);
        }

        @Override
        public Object getCellEditorValue() {
            return comboBox.getSelectedItem();
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            comboBox.setSelectedItem(value);
            return comboBox;
        }

        @Override
        public boolean isCellEditable(EventObject e) {
            // Make the cell editable for all events
            return true;
        }
    }

    private UserStatus convertToUserStatusEnum(String status) {
        switch (status) {
            case "Active":
                return UserStatus.ACTIVE;
            case "Deactivated":
                return UserStatus.DEACTIVATED;
            default:
                // Handle unexpected cases, maybe throw an exception or return a default value
                return UserStatus.ACTIVE;
        }
    }

    public UserManagementUI() {
        initComponents();
        
        if (!SessionManager.isLoggedIn()) {
            lblName.setVisible(false);
        } else {
            lblName.setText(SessionManager.getLoggedInUsername());
        }
        
        programManager = new ProgramManager();
        displayUserInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblTravel = new javax.swing.JLabel();
        lblCentral = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        lblUsers = new javax.swing.JLabel();
        pnlSide = new javax.swing.JPanel();
        btnFlightManagement = new javax.swing.JButton();
        btnUserManagement = new javax.swing.JButton();
        btnHotelManagement = new javax.swing.JButton();
        btnAirportManagement = new javax.swing.JButton();
        btnAircraftManagement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setPreferredSize(new java.awt.Dimension(1536, 1536));
        pnlMain.setLayout(null);

        pnlHead.setBackground(new java.awt.Color(0, 0, 0));
        pnlHead.setPreferredSize(new java.awt.Dimension(1536, 100));
        pnlHead.setLayout(null);

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlHead.add(btnLogOut);
        btnLogOut.setBounds(1430, 30, 80, 30);

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlHead.add(btnHome);
        btnHome.setBounds(1350, 30, 80, 30);

        lblTravel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblTravel.setForeground(new java.awt.Color(255, 255, 255));
        lblTravel.setText("T R A V E L");
        pnlHead.add(lblTravel);
        lblTravel.setBounds(60, 30, 70, 16);

        lblCentral.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblCentral.setForeground(new java.awt.Color(255, 255, 255));
        lblCentral.setText("C E N T R A L");
        pnlHead.add(lblCentral);
        lblCentral.setBounds(60, 50, 90, 15);

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Full Name");
        pnlHead.add(lblName);
        lblName.setBounds(0, 40, 1540, 16);

        pnlMain.add(pnlHead);
        pnlHead.setBounds(0, 0, 1536, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        pnlMain.add(jScrollPane1);
        jScrollPane1.setBounds(530, 160, 880, 620);

        btnConfirm.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm Changes");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        pnlMain.add(btnConfirm);
        btnConfirm.setBounds(1290, 780, 120, 30);

        lblUsers.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setText("Users");
        pnlMain.add(lblUsers);
        lblUsers.setBounds(400, 70, 1140, 120);

        pnlSide.setBackground(new java.awt.Color(0, 0, 0));
        pnlSide.setLayout(null);

        btnFlightManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnFlightManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnFlightManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnFlightManagement.setText("FLIGHT MANAGEMENT");
        btnFlightManagement.setBorderPainted(false);
        btnFlightManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnFlightManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnFlightManagement);
        btnFlightManagement.setBounds(0, 210, 400, 40);

        btnUserManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnUserManagement.setText("USER MANAGEMENT");
        btnUserManagement.setBorderPainted(false);
        btnUserManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnUserManagement);
        btnUserManagement.setBounds(0, 250, 400, 40);

        btnHotelManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnHotelManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnHotelManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnHotelManagement.setText("HOTEL MANAGEMENT");
        btnHotelManagement.setBorderPainted(false);
        btnHotelManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnHotelManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnHotelManagement);
        btnHotelManagement.setBounds(0, 290, 400, 40);

        btnAirportManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnAirportManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnAirportManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnAirportManagement.setText("AIRPORT MANAGEMENT");
        btnAirportManagement.setBorderPainted(false);
        btnAirportManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnAirportManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirportManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnAirportManagement);
        btnAirportManagement.setBounds(0, 330, 400, 40);

        btnAircraftManagement.setBackground(new java.awt.Color(0, 0, 0));
        btnAircraftManagement.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnAircraftManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnAircraftManagement.setText("AIRCRAFT MANAGEMENT");
        btnAircraftManagement.setBorderPainted(false);
        btnAircraftManagement.setPreferredSize(new java.awt.Dimension(400, 40));
        btnAircraftManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAircraftManagementActionPerformed(evt);
            }
        });
        pnlSide.add(btnAircraftManagement);
        btnAircraftManagement.setBounds(0, 370, 400, 40);

        pnlMain.add(pnlSide);
        pnlSide.setBounds(0, 80, 400, 1460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        AdminOverviewUI adminOverview = new AdminOverviewUI();
        adminOverview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow == -1){
            System.out.println("No user selected. Please select a user before confirming changes.");
            return;
        }
        
        selectedStatus = (String) jTable1.getValueAt(selectedRow, 6);
        System.out.println("Selected Status for the selected user: " + selectedStatus);
        
        countUserBookingsAndUpdateStatus(selectedRow, selectedStatus);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnFlightManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightManagementActionPerformed
        FlightManagementUI flightManagement = new FlightManagementUI();
        flightManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlightManagementActionPerformed

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed

    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnHotelManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelManagementActionPerformed
        HotelManagementUI hotelManagement = new HotelManagementUI();
        hotelManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHotelManagementActionPerformed

    private void btnAirportManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirportManagementActionPerformed
        AirportManagementUI airportManagement = new AirportManagementUI();
        airportManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAirportManagementActionPerformed

    private void btnAircraftManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAircraftManagementActionPerformed
        AircraftManagementUI aircraftManagement = new AircraftManagementUI();
        aircraftManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAircraftManagementActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LogOutUI logOut = new LogOutUI();
        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void countUserBookingsAndUpdateStatus(int selectedRow, String selectedStatus) {
        
        int userID = (int) jTable1.getValueAt(selectedRow, 0);
        
        UserStatus updatedStatus = convertToUserStatusEnum(selectedStatus);
        programManager.updateUserStatus(userID, updatedStatus);

        // Refresh the table after updating status for all rows
        displayUserInformation();
    }

    private void displayUserInformation() {
        List<User> users = programManager.retrieveUsersInformation();

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 6 ? JComboBox.class : Object.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 6 && super.isCellEditable(row, column);
            }
        };

        model.addColumn("User ID");
        model.addColumn("First Name");
        model.addColumn("Last Name");
        model.addColumn("Email Address");
        model.addColumn("Phone Number");
        model.addColumn("Password");
        model.addColumn("Status");
        model.addColumn("Retrieval Question");
        model.addColumn("Retrieval Answer");
        model.addColumn("Bookings Count");

        String[] statusItems = {"Active", "Deactivated"};

        for (User user : users) {
            model.addRow(new Object[]{
                user.getUserID(),
                user.getFirstName(),
                user.getLastName(),
                user.getEmailAddress(),
                user.getPhoneNumber(),
                user.getPassword(),
                user.getUserStatus(),
                user.getRetrievalQuestion(),
                user.getRetrievalAnswer(),
                programManager.countUserBookings(user.getUserID())
            });
        }

        jTable1.setModel(model);

        // Set the Status column to use the StatusCellEditor
        int statusColumnIndex = model.findColumn("Status");
        JComboBox<String> statusComboBox = new JComboBox<>(statusItems);
        statusComboBox.setSelectedItem("Active"); // Set default status if needed
        jTable1.getColumnModel().getColumn(statusColumnIndex).setCellEditor(new DefaultCellEditor(statusComboBox));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAircraftManagement;
    private javax.swing.JButton btnAirportManagement;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnFlightManagement;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHotelManagement;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCentral;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
